### ISSUE TITLE
Hello there! I need help with gobber ore generation.

### ISSUE THREAD

**Issue by ScoRe187** [kwpugh/gobber#103]
Well, I installed the William Wythers Overhauled Overworld mod and now gobber ore is not generated in overworld. How should I set it up so that the ore starts generating in the world again? Everything is fine with Nether and End. 

Minecraft 1.17.1 Fabric

**Comment by Merkie** [comment]
The only way to change ore gen directly with that mod is to use the data pack instead of the mod and update the ore spawn for every biome. It’s a pain in the ass to do, id recommend trying a mod that replaces ore gen like the AdLods mod and edit the config to include gobber ore. I might replay back later with a version of the data pack that includes gobber ore.

**Comment by ScoRe187** [comment]
Where can I find AdLods mod? Can u give a link? 

> The only way to change ore gen directly with that mod is to use the data pack instead of the mod and update the ore spawn for every biome. It’s a pain in the ass to do, id recommend trying a mod that replaces ore gen like the AdLods mod and edit the config to include gobber ore. I might replay back later with a version of the data pack that includes gobber ore.

**Comment by kwpugh** [comment]
With Gobber and the 1.18 datapack, there is an option in the config for data pack ore spawning.  It may work, but no support.  The data pack is essentially a hack on Mojang's. part to replace parts of your game with beta code.  I will fully support the new worldgen when it is officially released with 1.18.0.
