### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by TookUrSweetRoll** [kwpugh/Gobber#4]
Deactivate mode (shift+right click) or key binding to turn off night vision/torches for tools?

Different modes for the RotM? Have 1x2xY, 3x3xY mode for tunneling.

A key binding for step assist would be nice. In explore mode it's indispensable, around the house I just die more often.

**Comment by kwpugh** [comment]
All great ideas.  As I am learning Java as I do the mod, I will need to figure out how to do these things.


Thank you.

**Comment by kwpugh** [comment]
Coming next update

Deactivate mode via sneak right-click on the following:
- Gobber and Nether Sword, Gobber and Nether Pickaxe, Gobber and Nether Hammer, Gobber and Nether Paxel (night vision)
- Paxel of the Stars (place torch)
- Sword of the Sniper (fire arrows)

They will also print better messages in chat to indicate what has changed

I'm not sure about different modes for the RotM, because it really wasn't intended for 3x3 tunneling, that's the hammer's job, but I will think on it.

I'll take a look at what I can do with the step assist.   You could always take your shoes off at home though.  ;)

**Comment by TookUrSweetRoll** [comment]
I appreciate all of your work, thank you. Good call on RotM, I have an enchanted hammer and a beacon now so it makes short work of the tunneling. :)

**Comment by kwpugh** [comment]
Added the new Medallion of Stepping in v60 as a way to enable/disable step height.   Step height is no longer on the armor boots.

**Comment by kwpugh** [comment]
Since the armors no longer have step assist, I'm closing this out.
