### ISSUE TITLE
[1.16.3] Ore Gen Issue?

### ISSUE THREAD

**Issue by kwpugh** [kwpugh/gobber#68]
Causing vanilla ores not to spawn

**Comment by Keparia** [comment]
The only other world-changing mod I have as well as gobber is better caves, but it has to be gobber, since once this mod is taken off the list, ores generate normally. Neither regular gobber or any vanilla ores will generate. The end and nether ores (including the end and nether gobbers) generate normally.
  I checked the config and the generate in world option is set to true. I tried changing it to false, loading a world, closing the game and changing the setting back to true, but it did not work. Here is my latest.log.

[latest.log](https://github.com/kwpugh/gobber/files/5248854/latest.log)

**Comment by kwpugh** [comment]
Please a list of all the mods you are using please.   I cannot replicate it, so it must be a bad interaction with another mod.

**Comment by kwpugh** [comment]
![2020-09-18_20 30 35](https://user-images.githubusercontent.com/8809210/93656169-ec956300-f9ed-11ea-9c5e-44f3f15276f4.png)

**Comment by kwpugh** [comment]
How are you checking to see if ores spawn?   Worldedit, /fill command, or something else?

**Comment by Keparia** [comment]
Yung's better caves (forge), snow under trees, blood particles, bookshelf, botany pots, comforts, falling tree, foodpouches, gravestone, optifine, rapid leaf decay, repurposed structures, ring of miner, total darkness, u team core, useful backpacks, xaeros minimap and xaeros world map, and x-ray mod I installed to check to see if ores were spawning quickly.
  I will go down the list right now, removing 1 mod at a time to find out which one is conflicting. I've used half of these mods on previous patches though, so I may be able to isolate the conflicting one quickly.

**Comment by kwpugh** [comment]
In 1.16.3, ore generation is a Biome function, so any mod that does anything based on Biomes can be the problem.  Still looking.

You can burrow a big hole with the:  /fill ~-8 0 ~-8 ~8 ~ ~8 minecraft:air replace minecraft:stone

replace the stone and the end to remove dirt, andesite, granite etc.   Nice way to get a clear view of ore spawn

**Comment by Keparia** [comment]
Okay it seems to be conflicting with optifine. I am using HD_U_G3, the most up-to-date version of optifine. I've used both mods in the past (1.15.2) without any issue. Don't understand why it would affect anything now.

**Comment by kwpugh** [comment]
In 1.16.3, since ore spawn is still kind of broken, modders are using an access transformer to get at a private method.  It may be causing conflict with the MANY access transformers Optifine uses to work its magic

**Comment by kwpugh** [comment]
Its very hard to troubleshoot with Optifine in the pictures because it is closed source and we have no clue what it is doing

**Comment by Keparia** [comment]
I'm going to look into the options for optifine and see if there's a work-around so I can use both mods, because these 2 are my most favorite mods and I would like to use both of them. Thank you for helping me narrow it down and explaining how these things interact with each other.

**Comment by kwpugh** [comment]
Sure, no problem.   Please post on update here if/when you find something, I'm curious to know as well.

**Comment by Keparia** [comment]
Will do, I'll mess around with the settings today and tomorrow and see if something works. I will post here if I do find a solution.

**Comment by Keparia** [comment]
Okay, that was quicker than I thought. The issue appears to have been fixed. All I have done since my last comment was install optiforge (didn't seem to do anything though). I created a new world, no ores were spawning in as usual. I turned off my active shader, closed minecraft, re-opened it, started a new world (with the shader off) and ores spawned in like they are supposed to. 

The weird part is I re-activated the shader I was using and created a new world and all the ores were generating normally. I guess this is kind of like turning it off and on again but with shaders and mods, lol. I don't why that worked, but it did.
